---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-run-as-non-root
  annotations:
    policies.kyverno.io/title: Run As Non-Root
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Containers must be required to run as a non-root user to prevent potential privilege escalation.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Security violation: Running containers as root (UID 0) is prohibited. Please set securityContext.runAsNonRoot to true."
        pattern:
          spec:
            =(securityContext):
              =(runAsNonRoot): true
            containers:
              - =(securityContext):
                  =(runAsNonRoot): true